spring:
  application:
    name: AddressBook
  datasource:
    url: 'jdbc:postgresql://localhost:5432/addressbook'
    username: addressbook
    password: addressbookadmin
server:
  context-path: /addressbook
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: addressbook
    key-store-type: PKCS12
    key-alias: addressbook

flyway:
  clean-on-validation-error: true